#!/usr/bin/env python3

import roslib
import rospy

from led_control_node.main import LedControlNode

NODE_NAME = 'led_control_node'
roslib.load_manifest(NODE_NAME)

if __name__ == '__main__':
    rospy.init_node(NODE_NAME)
    try:
        node = LedControlNode()
    except rospy.ROSInterruptException:
        pass
